"""Enforce customer_id on checkout_sessions

Revision ID: 8fc37ef17163
Revises: e5856d5d5c09
Create Date: 2026-03-14 21:31:14.676519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fc37ef17163'
down_revision: Union[str, None] = 'e5856d5d5c09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkout_sessions', sa.Column('customer_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_checkout_sessions_customer_id'), 'checkout_sessions', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'checkout_sessions', 'customers', ['customer_id'], ['id'])
    op.drop_column('checkout_sessions', 'customer_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkout_sessions', sa.Column('customer_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'checkout_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_checkout_sessions_customer_id'), table_name='checkout_sessions')
    op.drop_column('checkout_sessions', 'customer_id')
    # ### end Alembic commands ###
