"""Add hashed_password to Customer

Revision ID: d06d205ef83f
Revises: 8fc37ef17163
Create Date: 2026-03-15 01:15:11.551560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd06d205ef83f'
down_revision: Union[str, None] = '8fc37ef17163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('api_keys_key_hash_key', 'api_keys', type_='unique')
    op.add_column('customers', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.drop_constraint('customers_stripe_customer_id_key', 'customers', type_='unique')
    op.drop_index('ix_customers_stripe_customer_id', table_name='customers')
    op.create_index(op.f('ix_customers_stripe_customer_id'), 'customers', ['stripe_customer_id'], unique=True)
    op.drop_constraint('payments_idempotency_key_key', 'payments', type_='unique')
    op.drop_constraint('payments_stripe_payment_intent_id_key', 'payments', type_='unique')
    op.drop_index('ix_payments_idempotency_key', table_name='payments')
    op.create_index(op.f('ix_payments_idempotency_key'), 'payments', ['idempotency_key'], unique=True)
    op.drop_index('ix_payments_stripe_payment_intent_id', table_name='payments')
    op.create_index(op.f('ix_payments_stripe_payment_intent_id'), 'payments', ['stripe_payment_intent_id'], unique=True)
    op.drop_constraint('receipts_payment_id_key', 'receipts', type_='unique')
    op.drop_constraint('receipts_receipt_number_key', 'receipts', type_='unique')
    op.drop_index('ix_receipts_payment_id', table_name='receipts')
    op.create_index(op.f('ix_receipts_payment_id'), 'receipts', ['payment_id'], unique=True)
    op.drop_index('ix_receipts_receipt_number', table_name='receipts')
    op.create_index(op.f('ix_receipts_receipt_number'), 'receipts', ['receipt_number'], unique=True)
    op.drop_constraint('refunds_idempotency_key_key', 'refunds', type_='unique')
    op.drop_constraint('refunds_stripe_refund_id_key', 'refunds', type_='unique')
    op.drop_index('ix_refunds_idempotency_key', table_name='refunds')
    op.create_index(op.f('ix_refunds_idempotency_key'), 'refunds', ['idempotency_key'], unique=True)
    op.drop_index('ix_refunds_stripe_refund_id', table_name='refunds')
    op.create_index(op.f('ix_refunds_stripe_refund_id'), 'refunds', ['stripe_refund_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refunds_stripe_refund_id'), table_name='refunds')
    op.create_index('ix_refunds_stripe_refund_id', 'refunds', ['stripe_refund_id'], unique=False)
    op.drop_index(op.f('ix_refunds_idempotency_key'), table_name='refunds')
    op.create_index('ix_refunds_idempotency_key', 'refunds', ['idempotency_key'], unique=False)
    op.create_unique_constraint('refunds_stripe_refund_id_key', 'refunds', ['stripe_refund_id'])
    op.create_unique_constraint('refunds_idempotency_key_key', 'refunds', ['idempotency_key'])
    op.drop_index(op.f('ix_receipts_receipt_number'), table_name='receipts')
    op.create_index('ix_receipts_receipt_number', 'receipts', ['receipt_number'], unique=False)
    op.drop_index(op.f('ix_receipts_payment_id'), table_name='receipts')
    op.create_index('ix_receipts_payment_id', 'receipts', ['payment_id'], unique=False)
    op.create_unique_constraint('receipts_receipt_number_key', 'receipts', ['receipt_number'])
    op.create_unique_constraint('receipts_payment_id_key', 'receipts', ['payment_id'])
    op.drop_index(op.f('ix_payments_stripe_payment_intent_id'), table_name='payments')
    op.create_index('ix_payments_stripe_payment_intent_id', 'payments', ['stripe_payment_intent_id'], unique=False)
    op.drop_index(op.f('ix_payments_idempotency_key'), table_name='payments')
    op.create_index('ix_payments_idempotency_key', 'payments', ['idempotency_key'], unique=False)
    op.create_unique_constraint('payments_stripe_payment_intent_id_key', 'payments', ['stripe_payment_intent_id'])
    op.create_unique_constraint('payments_idempotency_key_key', 'payments', ['idempotency_key'])
    op.drop_index(op.f('ix_customers_stripe_customer_id'), table_name='customers')
    op.create_index('ix_customers_stripe_customer_id', 'customers', ['stripe_customer_id'], unique=False)
    op.create_unique_constraint('customers_stripe_customer_id_key', 'customers', ['stripe_customer_id'])
    op.drop_column('customers', 'hashed_password')
    op.create_unique_constraint('api_keys_key_hash_key', 'api_keys', ['key_hash'])
    # ### end Alembic commands ###
